"""empty message

Revision ID: 2e0718079933
Revises: f09c73c60c4f
Create Date: 2025-01-05 15:09:35.279126

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2e0718079933'
down_revision: Union[str, None] = 'f09c73c60c4f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('_name_lat_lon_uc', 'location', type_='unique')
    op.create_unique_constraint('name_user_uc', 'location', ['name', 'latitude', 'longitude', 'user_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('name_user_uc', 'location', type_='unique')
    op.create_unique_constraint('_name_lat_lon_uc', 'location', ['name', 'latitude', 'longitude'])
    # ### end Alembic commands ###
