"""empty message

Revision ID: f09c73c60c4f
Revises: 0d7abda2041b
Create Date: 2024-12-03 21:29:19.127370

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f09c73c60c4f'
down_revision: Union[str, None] = '0d7abda2041b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('_name_lat_lon_uc', 'location', ['name', 'latitude', 'longitude'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('_name_lat_lon_uc', 'location', type_='unique')
    # ### end Alembic commands ###
